### PR TITLE
Missing dependency. Combine 2 launch files into one.

### PR DESCRIPTION
**Pull request by 130s**
`motoman_sim.launch` does nothing but just launch a file from `motoman_sia20d_moveit_config` package, which I don't see a necessity.

Also adding a config for Travis. If this LGTY, any admins please enable Travis (at something like https://travis-ci.org/profile/ros-industrial-consortium) by a single click to get the checking started.

### CODE REVIEW

**Comment by JeroenDM** [comment]
I think it can be useful to have the two separate launch files.  Then you can run the tutorial several times in a separate console, while not having to wait for rviz and moveit every time. This can also be achieved by running the proposed single launch file and then for rerunning, using rosrun in a separate console and using: `rosrun descartes_tutorials tutorial1`. (Or, a third way, let the tutorial auto-repeat itself until it is stopped from console.) I don't know what's best.

**Comment by Jmeyer1292** [comment]
These things are fine, but the real problem is that this tutorial does not reflect how the Descartes package is used in production at all. It needs closed form kinematic models and more interesting trajectories.

**Comment by JeroenDM** [comment]
The missing dependency should be added maybe for the `rosdep` command in [the tutorial](http://wiki.ros.org/descartes/Tutorials/Getting%20Started%20with%20Descartes) to work I think.

**Comment by yijiangh** [comment]
@Jmeyer1292 : @JeroenDM has expanded the tutorial with another tutorial application - [here](https://github.com/JeroenDM/descartes_tutorials/tree/6b07a57a9b4db0cc7966dafab2a299507f4c2671) [1], with kuka robot equipped with welding torch end effector and closed-form ik model (check [this line](https://github.com/JeroenDM/descartes_tutorials/blob/6b07a57a9b4db0cc7966dafab2a299507f4c2671/descartes_tutorials/src/tutorial2.cpp#L152) of code). Although the example has issue with collision avoidance and desire process path is not interesting enough, I think it's still a good complement to current tutorial. @JeroenDM Could you please try to fix the collision issue and creat a pull request?

[1] https://github.com/JeroenDM/descartes_tutorials

**Pull request merged**
