### PR TITLE
Gives build targets in CMakeLists more specific names

### PR DESCRIPTION
**Pull request by Jmeyer1292**
This PR addresses issue #2 by prefixing the target names in descartes_tutorial1 with 'descartes_'.

### CODE REVIEW

**Comment by Jmeyer1292** [comment]
is having an executable with the same name as the package a bad idea?

**Comment by gavanderhoorn** [comment]
@Jmeyer1292: not sure, but it is unnecessary in any case. See [my comment](https://github.com/ros-industrial/ros_industrial_issues/issues/8#issuecomment-29725206) on ros-industrial/ros_industrial_issues#8: the prefix can (and should be) stripped of the actual filename of the binary.

**Comment by Jmeyer1292** [comment]
@gavanderhoorn I changed the targets to model the fanuc example in your link. Please let me know if  I'm on the right track,

**Comment by gavanderhoorn** [comment]
Yep. Squash, merge.

+1.

**Comment by Jmeyer1292** [comment]
Thank you for your support.

**Pull request merged**
